application: extractor
version: extract
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webob
  version: latest
- name: jinja2
  version: 2.6

builtins:
- remote_api: on

handlers:
- url: .*
  script: main.app
  login: admin

